# Generated by Django 3.1.4 on 2020-12-07 04:04

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_email', models.EmailField(blank=True, max_length=254)),
                ('teacher_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_description', models.CharField(max_length=100)),
                ('teacher', models.ManyToManyField(to='HomeworkManagementApp.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=50)),
                ('assignment_description', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('assignment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeworkManagementApp.classroom')),
            ],
        ),
    ]
