# Generated by Django 3.1.4 on 2020-12-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_syllabus',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
