# Generated by Django 3.1.4 on 2020-12-06 20:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(default='abdullahqsiddiqui@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2242085112', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
