# Generated by Django 3.1.4 on 2020-12-07 05:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0002_auto_20201207_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 5, 40, 40, 546963, tzinfo=utc)),
        ),
    ]
