# Generated by Django 3.1.4 on 2020-12-06 21:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0003_auto_20201206_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
