# Generated by Django 3.1.4 on 2020-12-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0004_auto_20201206_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ManyToManyField(to='HomeworkManagementApp.Teacher'),
        ),
    ]
