# Generated by Django 4.0 on 2021-12-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0004_auto_20201207_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
