# Generated by Django 3.1.4 on 2020-12-06 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomeworkManagementApp', '0005_auto_20201206_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='user',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='HomeworkManagementApp.student'),
            preserve_default=False,
        ),
    ]
