# Generated by Django 4.0 on 2021-12-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0005_alter_assignment_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
