# Generated by Django 3.1.4 on 2020-12-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0006_auto_20201206_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
    ]
