# Generated by Django 3.1.4 on 2020-12-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0007_remove_classroom_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
