# Generated by Django 3.1.4 on 2020-12-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0009_auto_20201206_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
