# Generated by Django 4.0 on 2021-12-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0011_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
