# Generated by Django 4.0 on 2021-12-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
