# Generated by Django 4.0 on 2022-01-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeworkManagementApp', '0015_assignment_completed_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
